---
framework: jest
licenseTier: xsmall
postMerge: 
  pattern: 
    - "./src/*.test.js"
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./src/*.test.js"
preRun:
     command:
        - npm install
postRun:
     command:
        - node --version
version: 2.1
